Online_Auction_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
]

home_page/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login/', views.log_in, name='login'),
    path('register/', views.register, name='register'),
    path('register_pi/<str:username>/', views.register_pi, name='register_pi'),
    path('logout/', views.log_out, name='logout'),
    path('forgot_pass/', views.forgot_pass, name='forgot_pass'),
    path('reset_pass/', views.reset_pass, name='reset_pass'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('create_auction/', views.create_auction, name='create_auction'),
    path('auction_details/<int:auction_id>/', views.auction_details, name='auction_details'),
    path('place_bid/<int:auction_id>/', views.place_bid, name='place_bid'),
    path('auto_update_auction/', views.auto_update_auction, name='auto_update_auction'),
    path('manual_update_auction/', views.manual_update_auction, name='manual_update_auction'),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('add_to_watchlist/<int:auction_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/<int:auction_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('withdraw_from_auction/<int:auction_id>/', views.withdraw_from_auction, name='withdraw_from_auction'),
    path('saved_auction/', views.saved_auction, name='saved_auction'),
    path('edit_auction/<int:auction_id>/', views.edit_auction, name='edit_auction'),
    path('completed_auction/', views.completed_auction, name='completed_auction'),
    path('completed_auction_details/<int:auction_id>/', views.completed_auction_details, name='completed_auction_details'),
    path('ongoing_auction/', views.ongoing_auction, name='ongoing_auction'),
    path('change_pass/', views.change_pass, name='change_pass'),
    path('cart/', views.cart, name='cart'),
    path('cart_auction_details/<int:auction_id>/', views.cart_auction_details, name='cart_auction_details'),
    path('checkout/<int:auction_winner_id>/', views.checkout, name='checkout'),
    path('remove_from_cart/<int:auction_winner_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('get_wallet_balance/', views.get_wallet_balance, name='get_wallet_balance'),
    path('wallet/', views.wallet, name='wallet'),
    path('reload_wallet/', views.reload_wallet, name='reload_wallet'),
    path('to_deliver/', views.to_deliver, name='to_deliver'),
    path('deliver_auction_details/<int:auction_winner_id>/', views.deliver_auction_detail, name='deliver_auction_details'),
    path('to_receive/', views.to_receive, name='to_receive'),
    path('receive_auction_details/<int:auction_winner_id>/', views.receive_auction_details, name='receive_auction_details'),
    path('report/', views.report, name='report'),
    path('view_profile/', views.view_profile, name='view_profile'),
    path('admin_home/', views.home_page, name='admin_home'),
    path('manage_user/', views.manage_user, name='manage_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('view_user_profile/<int:user_id>/', views.view_user_profile, name='view_user_profile'),
    path('manage_trans/', views.manage_trans, name='manage_trans'),
    path('approve_trans/<int:transaction_id>/', views.approve_trans, name='approve_trans'),
    path('decline_trans/<int:transaction_id>/', views.decline_trans, name='decline_trans'),
    path('manage_report/', views.manage_report, name='manage_report'),
    path('delete_report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('view_report/<int:report_id>/', views.view_report, name='view_report'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_page/models.py
import datetime
from django.db import models
from django.contrib.auth.hashers import check_password as check_password_hash
from django.contrib.auth.hashers import make_password
from django.core.validators import MinValueValidator

class OASuser(models.Model):
    username = models.CharField(max_length=20, unique=True)
    userPass = models.CharField(max_length=255)
    fName = models.CharField(max_length=50)
    lName = models.CharField(max_length=50)
    date_of_birth = models.DateField(default=datetime.date.today)
    gender = models.CharField(max_length=10)
    phoneNo = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.TextField()
    last_login = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    balance = models.DecimalField(max_digits=65, decimal_places=2, default=0)

 
    def __str__(self):
        return self.username
    
    def check_password(self, raw_password):
        return check_password_hash(raw_password, self.userPass)

    def get_username(self):
        return self.username

    @property
    def is_authenticated(self):
        return self.is_active
    
    def set_password(self, raw_password):
        self.userPass = make_password(raw_password)

class OASauction(models.Model):
    item_name = models.CharField(max_length=100)
    item_desc = models.TextField(max_length=200)
    item_cat = models.CharField(max_length=50)
    start_bid = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    current_bid = models.DecimalField(max_digits=10, decimal_places=2, default=start_bid)
    second_highest_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(0)])
    current_bidder = models.ForeignKey(OASuser, on_delete=models.SET_NULL, null=True, blank=True, related_name='bidding_auctions')
    second_highest_bidder = models.ForeignKey(OASuser, on_delete=models.SET_NULL, null=True, blank=True)
    seller = models.ForeignKey(OASuser, on_delete=models.CASCADE, related_name='seller_auctions')
    auction_created_time = models.DateTimeField(null=True, blank=True)
    auction_end_time = models.DateTimeField()
    comment = models.TextField(blank=True, null=True)
    ratings = models.IntegerField(null=True, blank=True)  
    picture1 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture2 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture3 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture4 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture5 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture6 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    picture7 = models.ImageField(upload_to='auction_pictures/', blank=True, null=True)
    is_saved = models.BooleanField(default=False)
    is_ongoing = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.current_bid = self.start_bid
        super().save(*args, **kwargs)

class OASwatchlist(models.Model):
    user = models.ForeignKey(OASuser, on_delete=models.CASCADE)
    auction = models.ForeignKey(OASauction, on_delete=models.CASCADE)

class OASauctionWinner(models.Model):
    auction = models.OneToOneField(OASauction, on_delete=models.CASCADE)
    winner = models.ForeignKey(OASuser, on_delete=models.CASCADE, blank=True, null=True)
    winning_bid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    buyer_name = models.CharField(max_length=100, blank=True, null=True)
    buyer_phone = models.CharField(max_length=15, blank=True, null=True)
    buyer_address = models.TextField(blank=True, null=True)
    is_checkout = models.BooleanField(default=False)
    is_delivered = models.BooleanField(default=False)
    is_received = models.BooleanField(default=False)
    checkout_deadline = models.DateTimeField(null=True, blank=True)

class OAStransaction(models.Model):
    main_user = models.ForeignKey(OASuser, on_delete=models.CASCADE, related_name='transactions_as_main')
    second_user = models.ForeignKey(OASuser, on_delete=models.CASCADE, related_name='transactions_as_second')
    transaction_type = models.CharField(max_length=10)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)

class OASreport(models.Model):
    user = models.ForeignKey(OASuser, on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title



    # python manage.py makemigrations
    # python manage.py migrate

    # python manage.py runserver

    # python manage.py shell
    # from home_page.models import OASuser
    # OASuser.objects.all()
    

home_page/templates/admin_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <title>Admin Page | Bidify</title>
</head>
<body>
    <ul class="navbar">
            <li style="float:left"><a><img src="{% static 'image/profile_icon.png' %}" class="profile-icon">
            &nbsp;&nbsp;Welcome, ADMIN
            </a></li>
            <li style="float:left" class="dropdown">
            <a href="javascript:void(0)" class="dropbtn"><img src="{% static 'image/settings_icon.png' %}" class="settings-icon">
                &nbsp;Settings
            </a>
            <div class="dropdown-content">
                <a href="{% url 'change_pass' %}">Change Password</a>
                <a href="{% url 'logout' %}">Logout</a>
            </div>
        </li>
        <li style="float:right"><a href="{% url 'manage_user' %}">Manage Users</a></li>
        <li style="float:right"><a href="{% url 'manage_trans' %}">Manage Transactions</a></li>
        <li style="float:right"><a href="{% url 'manage_report' %}">Manage Reports</a></li>
    </ul>
        
        <div class="header-content">
            <img src="{% static 'image/bidify.png' %}" alt="Bidify Logo" class="logo">
        </div>
        <form method="GET" action="{% url 'home_page' %}">
            <input type="text" name="q" placeholder="Search for anything" value="{{ query }}">
            <select name="category">
                <option value="">All Categories</option>
                {% for category in categories %}
                    <option value="{{ category }}" {% if selected_category == category %}selected{% endif %}>{{ category }}</option>
                {% endfor %}
            </select>
            <button type="submit">Search</button>
            {% if query or selected_category %}
                <a href="{% url 'home_page' %}"><button type="button">Clear Results</button></a>
            {% endif %}
        </form>
    <hr>

    {% if query or selected_category %}
        {% if not active_auctions %}
            <h2>No results found for "{{ query }}", "{{ selected_category }}".</h2>
        {% else %}
            <h2>Search Results:</h2>
        {% endif %}
    {% endif %}
    
    <ul class="auction-list">
        {% for auction in active_auctions %}
            <li>
                <a href="{% url 'auction_details' auction.id %}">
                    <img src="{{ auction.picture1.url }}" alt="Item Picture 1" class="item-pic">
                    <h2>{{ auction.item_name }}</h2>
                    <p>Current Bid: RM{{ auction.current_bid }}</p>
                    <p>End Time: {{ auction.auction_end_time }}</p>
                </a>
            </li>
        {% endfor %}
    </ul>

    <script>
        setInterval(function() {
            fetch("{% url 'auto_update_auction' %}")
            .then(response => {
                if (response.ok) {
                    window.location.reload();
                } else {
                    console.error("Failed to update auction status");
                }
            })
            .catch(error => console.error("Error:", error));
        }, 60000); 
    </script>
</body> 
</html>

home_page/templates/auction_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Auction Details | Bidify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auction_details.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <ul class="navbar">
        <li><a href="javascript:history.back()"> &lt; Back</a></li>
        <li><a href="{% url 'home_page' %}"><img src="{% static 'image/bidify_white.png' %}" class="bidify-white-icon"></a></li>
        <li><a href="{% url 'watchlist' %}"><img src="{% static 'image/watchlist_icon.png' %}" class="watchlist-icon">  Watchlist</a></li>
        <li><a href="{% url 'cart' %}"><img src="{% static 'image/cart_icon.png' %}" class="cart-icon">  Cart</a></li>
        <li><a href="{% url 'wallet' %}"><img src="{% static 'image/wallet_icon.png' %}" class="wallet-icon">  RM{{ user.balance }}</a></li>
    </ul>
    
    <div class="auction-details">
        <div class="row">
            <div class="col-md-6">
                <div id="itemCarousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for picture in pictures %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img src="{{ picture }}" alt="Item Picture {{ forloop.counter }}">
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#itemCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#itemCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <h2 style="color: #2f3651;"><b>{{ auction.item_name }}</b></h2>
                <p class="category">{{ auction.item_cat }}</p>
                <hr>
                <p class="description">{{ auction.item_desc }}</p>
                <hr>
                <h5 style="color: #2f3651;">Auction Info</h5>
                <p>Seller: <b>{{ seller_username }}</b></p>
                <p>Time Left: <b><span id="countdown"></span></b> | <b>{{ auction.auction_end_time|date:"d M Y, h:iA" }}</b></p>
                <p>Starting Bid: <b>RM {{ auction.start_bid }}</b></p>
                <p>Current Bid: <b>RM {{ auction.current_bid }}</b></p>
                <div class="btn-section">
                    <form action="{% url 'place_bid' auction.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="bid-amount">Bid Amount: <b>RM</b></label>
                            <input type="number" step="0.10" min="{{ auction.current_bid }}" name="bid_amount" placeholder="Enter amount more than RM{{ auction.current_bid }}">
                            {% if error_message %}
                                <p class="error-message">{{ error_message }}</p>
                            {% elif success_message %}
                                <p class="success-message">{{ success_message }}</p>
                            {% endif %}
                        </div>
                        <button type="submit" class="place-bid-btn">Place Bid</button>
                    </form>
                    
                    {% if in_watchlist %}
                        <form method="post" action="{% url 'remove_from_watchlist' auction.id %}">
                            {% csrf_token %}
                            <button class="add-watchlist-btn" type="submit" name="action" value="remove" id="remove-watchlist-button">Remove from Watchlist</button>
                        </form>
                    {% else %}
                        <form method="post" action="{% url 'add_to_watchlist' auction.id %}">
                            {% csrf_token %}
                            <button class="add-watchlist-btn" type="submit" name="action" value="add" id="add-watchlist-button">Add to Watchlist</button>
                        </form>
                    {% endif %}

                    {% if request.user == auction.current_bidder %}
                        <form id="withdraw-form" method="post" action="{% url 'withdraw_from_auction' auction.id %}">
                            {% csrf_token %}
                            <button class="add-watchlist-btn" type="button" id="withdraw-button">Withdraw from Auction</button>
                        </form>
                    {% endif %}

                    {% if request.user == auction.seller %}
                        <form id="delete-form-{{ auction.id }}" method="post" action="{% url 'auction_details' auction.id %}">
                            {% csrf_token %}
                            <button class="delete-btn" type="submit" name="action" value="delete" data-user-id="{{ auction.id }}" id="delete-btn">Delete Auction</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <script>
        function goBack() {
            window.history.back();
        }
    </script>

    <script>
        function updateCountdown(endTime) {
            var now = new Date().getTime();

            var timeDifference = endTime - now;

            if (timeDifference <= 0) {
                document.getElementById("countdown").innerHTML = "Auction ended";
                return;
            }

            var days = Math.floor(timeDifference / (1000 * 60 * 60 * 24));
            var hours = Math.floor((timeDifference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((timeDifference % (1000 * 60)) / 1000);

            var countdown = "";
            if (days < 2) {
                countdown += days + " day ";
            }
            else if (days >= 2) {
                countdown += days + " days ";
            }
            if (hours < 2) {
                countdown += hours + " hr ";
            }
            else if (hours >= 2) {
                countdown += hours + " hrs ";
            }
            if (minutes < 2) {
                countdown += minutes + " min ";
            }
            else if (minutes >= 2) {
                countdown += minutes + " mins ";
            }
            countdown += seconds + " sec";

            document.getElementById("countdown").innerHTML = countdown;

            setTimeout(function() {
                updateCountdown(endTime);
            }, 1000);
        }

        var auctionEndTime = new Date("{{ auction.auction_end_time|date:'Y-m-d H:i:s' }}").getTime();
        
        updateCountdown(auctionEndTime);
    </script>

    <script>
        const withdrawButton = document.getElementById('withdraw-button');

        withdrawButton.addEventListener('click', function() {
            const confirmed = confirm('Are you sure you want to withdraw from the auction?');
            
            if (confirmed) {
                document.getElementById('withdraw-form').submit();
            }
        });
    </script>

    <script>
        document.querySelectorAll('.delete-btn').forEach(function(button) {
                button.addEventListener('click', function(event) {
                    const confirmed = confirm('Are you sure you want to delete this auction?');
                    
                    if (!confirmed) {
                        event.preventDefault();
                    }
                });
            });
    </script>

    <script>
        const addWatchlistButton = document.getElementById('add-watchlist-button');

        addWatchlistButton.addEventListener('click', function() {
            const confirmed = alert('Item added to watchlist');
        });
    </script>

    <script>
        const removeWatchlistButton = document.getElementById('remove-watchlist-button');

        removeWatchlistButton.addEventListener('click', function() {
            const confirmed = alert('Item removed from watchlist');
        });
    </script>
</body>
</html>

home_page/templates/cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <title>Cart | Bidify</title>
</head>
<body>
    <ul class="navbar">
        <li style="float:left"><a href="{% url 'home_page' %}"> &lt; Back</a></li>
        <li style="float:left"><a href="{% url 'view_profile' %}"><img src="{% static 'image/profile_icon.png' %}" class="profile-icon"></a></li>
        <li style="float:left" class="dropdown">
            <a href="javascript:void(0)" class="dropbtn"><img src="{% static 'image/settings_icon.png' %}" class="settings-icon">
                &nbsp;Settings
            </a>
            <div class="dropdown-content">
                <a href="{% url 'edit_profile' %}">Edit Profile</a>
                <a href="{% url 'change_pass' %}">Change Password</a>
                <a href="{% url 'report' %}">Report</a>
                <a href="{% url 'logout' %}" class="logout-btn">Logout</a>
            </div>
        </li>
        <li style="float:right"><a href="{% url 'wallet' %}"><img src="{% static 'image/wallet_icon.png' %}" class="wallet-icon">  RM{{ user.balance }}</a></li>
        <li style="float:right"><a href="{% url 'watchlist' %}"><img src="{% static 'image/watchlist_icon.png' %}" class="cart-icon">  Watchlist</a></li>
        <li style="float:right"><a href="{% url 'to_receive' %}">To Receive</a></li>
        <li style="float:right"><a href="{% url 'to_deliver' %}">To Deliver</a></li>
        <li style="float:right" class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Sell</a>
            <div class="dropdown-content">
                <a href="{% url 'create_auction' %}">Create Auction</a>
                <a href="{% url 'saved_auction' %}">Saved Auction</a>
                <a href="{% url 'ongoing_auction' %}">Ongoing Auction</a>
                <a href="{% url 'completed_auction' %}">Completed Auction</a>
            </div>
        </li>
    </ul>
        
    <div class="header-content">
        <img src="{% static 'image/bidify.png' %}" alt="Bidify Logo" class="logo">
    </div>
    <hr>
    <h1 style="color: #2f3651;">Cart</h1>
    <ul class="auction-list">
        {% for auction in won_auctions %}
            <li>
                <a href="{% url 'cart_auction_details' auction.auction.id %}">
                    <img src="{{ auction.auction.picture1.url }}" class="item-pic">
                    <h2>{{ auction.auction.item_name }}</h2><br>
                    <p class="auction-desc">Price: <b>RM {{ auction.winning_bid }}</b></p>
                    <p class="auction-desc">Seller: <b>{{ auction.auction.seller.username }}</b></p>
                    <p class="auction-desc">Checkout Deadline: <b>{{ auction.checkout_deadline|date:"d M Y, h:iA"}}</b></p>
                </a>
            </li>
        {% endfor %}
    </ul>

    <img onclick="topFunction()" id="backToTopBtn" title="Back to Top" src="{% static 'image/back_to_top_icon.png' %}" class="back-to-top-icon">

    <script src="{% static 'js/back_to_top.js' %}"></script>

    <script>
        fetch("{% url 'get_wallet_balance' %}")
            .then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Failed to fetch wallet balance');
                }
            })
            .then(data => {
                document.getElementById('wallet-balance').textContent = `RM${data.balance}`;
            })
            .catch(error => {
                console.error('Error:', error);
            });
    </script>

    <script>
        document.querySelectorAll('.logout-btn').forEach(function(button) {
                button.addEventListener('click', function(event) {
                    const confirmed = confirm('Logout from your account?');
                    
                    if (!confirmed) {
                        event.preventDefault();
                    }
                });
            });
    </script>
</body> 
</html>

home_page/templates/edit_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile | Bidify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/register_pi.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
</head>

<body>
    <img src="{% static 'image/bidify.png' %}" alt="bidify" class="logo">

    <div class="rounded-box">
        <h2>Edit Profile</h2><br>
        <form method="post" action="{% url 'edit_profile' %}">
            {% csrf_token %}
            <div class="form-row1">
                {{ form.fName.label_tag }}
                {{ form.fName }}
                <span class="tab"></span>
                {{ form.lName.label_tag }}
                {{ form.lName }}
            </div><br><br>
            <div class="form-row2">
                {{ form.date_of_birth.label_tag }}
                {{ form.date_of_birth }}
                <span class="tab"></span>
                {{ form.gender.label_tag }}
                {{ form.gender }}
                <span class="tab"></span>
                {{ form.phoneNo.label_tag }}
                {{ form.phoneNo }}
            </div><br><br>
            <div class="form-row3">
                {{ form.email.label_tag }}
                {{ form.email }}
                <span class="tab"></span><span class="tab"></span>
                {{ form.address.label_tag }}
                {{ form.address }}
            </div><br><br>
            <button type="submit" name="register">Submit</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_date_of_birth').datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0" 
            });
        });
    </script>
</body>
</html>

home_page/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | Bidify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
</head>

<body>
    <img src="{% static 'image/bidify.png' %}" alt="bidify" class="logo">

    <div class="rounded-box">
        <h2>Login</h2><br>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form }}
            <p class="error">{{ error }}</p><br><br>
            <button type="submit" name="login-button">Login</button>
        </form>
        
        <p><a href="{% url 'register' %}" class="register">Register</a> <b>|</b> <a href="{% url 'forgot_pass' %}" class="forgot-password">Forgotten Password</a></p>
    </div>
</body>
</html>

home_page/templates/register_pi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Information | Bidify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/register_pi.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
</head>

<body>
    <img src="{% static 'image/bidify.png' %}" alt="bidify" class="logo">

    <div class="rounded-box">
        <h2>Personal Information</h2><br>
        <form method="post" action="{% url 'register_pi' username=username %}">
            {% csrf_token %}
            <div class="form-row1">
                {{ form.fName.label_tag }}
                {{ form.fName }}
                <span class="tab"></span>
                {{ form.lName.label_tag }}
                {{ form.lName }}
            </div><br><br>
            <div class="form-row2">
                {{ form.date_of_birth.label_tag }}
                {{ form.date_of_birth }}
                <span class="tab"></span>
                {{ form.gender.label_tag }}
                {{ form.gender }}
                <span class="tab"></span>
                {{ form.phoneNo.label_tag }}
                {{ form.phoneNo }}
            </div><br><br>
            <div class="form-row3">
                {{ form.email.label_tag }}
                {{ form.email }}
                <span class="tab"></span><span class="tab"></span>
                {{ form.address.label_tag }}
                {{ form.address }}
            </div><br><br>
            <button type="submit" name="register">Register</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_date_of_birth').datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0" // Allow selection from 100 years ago to today
            });
        });
    </script>
</body>
</html>